# Name your project
name: 'dbt_sample'
version: '1.0.0'
config-version: 2

# dbt profile
profile: 'dbt_sample'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean
clean-targets:
  - "target"
  - "dbt_packages"

# Models config
models:
  dbt_sample:

    # Catalog áp dụng cho toàn bộ models
    +catalog: workspace

    bronze:
      +schema: bronze

    silver:
      +schema: silver

    gold:
      +schema: gold
   # tất cả models trong folder gold dùng schema 'gold'
